"""Static ETF holdings data for portfolio breakdown analysis."""

ETF_HOLDINGS = {
    "SPY": {
        "name": "SPDR S&P 500 ETF",
        "total_holdings": 503,
        "holdings": [
            {"symbol": "AAPL", "weight": 7.1, "name": "Apple"}, {"symbol": "MSFT", "weight": 6.8, "name": "Microsoft"},
            {"symbol": "NVDA", "weight": 6.2, "name": "NVIDIA"}, {"symbol": "AMZN", "weight": 3.8, "name": "Amazon"},
            {"symbol": "META", "weight": 2.6, "name": "Meta Platforms"}, {"symbol": "GOOGL", "weight": 2.1, "name": "Alphabet A"},
            {"symbol": "GOOG", "weight": 1.8, "name": "Alphabet C"}, {"symbol": "BRK.B", "weight": 1.7, "name": "Berkshire Hathaway"},
            {"symbol": "LLY", "weight": 1.6, "name": "Eli Lilly"}, {"symbol": "AVGO", "weight": 1.5, "name": "Broadcom"},
            {"symbol": "JPM", "weight": 1.3, "name": "JPMorgan Chase"}, {"symbol": "TSLA", "weight": 1.2, "name": "Tesla"},
            {"symbol": "UNH", "weight": 1.2, "name": "UnitedHealth"}, {"symbol": "XOM", "weight": 1.1, "name": "Exxon Mobil"},
            {"symbol": "V", "weight": 1.0, "name": "Visa"}, {"symbol": "MA", "weight": 0.9, "name": "Mastercard"},
            {"symbol": "PG", "weight": 0.9, "name": "Procter & Gamble"}, {"symbol": "COST", "weight": 0.9, "name": "Costco"},
            {"symbol": "JNJ", "weight": 0.8, "name": "Johnson & Johnson"}, {"symbol": "HD", "weight": 0.8, "name": "Home Depot"},
            {"symbol": "ABBV", "weight": 0.8, "name": "AbbVie"}, {"symbol": "WMT", "weight": 0.7, "name": "Walmart"},
            {"symbol": "NFLX", "weight": 0.7, "name": "Netflix"}, {"symbol": "BAC", "weight": 0.7, "name": "Bank of America"},
            {"symbol": "CRM", "weight": 0.7, "name": "Salesforce"},
        ],
    },
    "QQQ": {
        "name": "Invesco QQQ Trust",
        "total_holdings": 101,
        "holdings": [
            {"symbol": "AAPL", "weight": 8.9, "name": "Apple"}, {"symbol": "MSFT", "weight": 8.1, "name": "Microsoft"},
            {"symbol": "NVDA", "weight": 7.8, "name": "NVIDIA"}, {"symbol": "AMZN", "weight": 5.2, "name": "Amazon"},
            {"symbol": "META", "weight": 4.8, "name": "Meta Platforms"}, {"symbol": "AVGO", "weight": 4.2, "name": "Broadcom"},
            {"symbol": "GOOGL", "weight": 2.8, "name": "Alphabet A"}, {"symbol": "GOOG", "weight": 2.4, "name": "Alphabet C"},
            {"symbol": "TSLA", "weight": 2.7, "name": "Tesla"}, {"symbol": "COST", "weight": 2.5, "name": "Costco"},
            {"symbol": "NFLX", "weight": 2.0, "name": "Netflix"}, {"symbol": "AMD", "weight": 1.8, "name": "AMD"},
            {"symbol": "ADBE", "weight": 1.7, "name": "Adobe"}, {"symbol": "LIN", "weight": 1.5, "name": "Linde"},
            {"symbol": "QCOM", "weight": 1.5, "name": "Qualcomm"}, {"symbol": "TXN", "weight": 1.3, "name": "Texas Instruments"},
            {"symbol": "INTU", "weight": 1.3, "name": "Intuit"}, {"symbol": "ISRG", "weight": 1.2, "name": "Intuitive Surgical"},
            {"symbol": "AMAT", "weight": 1.2, "name": "Applied Materials"}, {"symbol": "BKNG", "weight": 1.1, "name": "Booking"},
            {"symbol": "PANW", "weight": 1.0, "name": "Palo Alto Networks"}, {"symbol": "ADP", "weight": 1.0, "name": "ADP"},
            {"symbol": "KLAC", "weight": 0.9, "name": "KLA Corp"}, {"symbol": "SNPS", "weight": 0.9, "name": "Synopsys"},
            {"symbol": "CRWD", "weight": 0.9, "name": "CrowdStrike"},
        ],
    },
    "VTI": {
        "name": "Vanguard Total Stock Market",
        "total_holdings": 3700,
        "holdings": [
            {"symbol": "AAPL", "weight": 6.5, "name": "Apple"}, {"symbol": "MSFT", "weight": 6.2, "name": "Microsoft"},
            {"symbol": "NVDA", "weight": 5.6, "name": "NVIDIA"}, {"symbol": "AMZN", "weight": 3.5, "name": "Amazon"},
            {"symbol": "META", "weight": 2.4, "name": "Meta Platforms"}, {"symbol": "GOOGL", "weight": 1.9, "name": "Alphabet A"},
            {"symbol": "BRK.B", "weight": 1.6, "name": "Berkshire Hathaway"}, {"symbol": "LLY", "weight": 1.5, "name": "Eli Lilly"},
            {"symbol": "AVGO", "weight": 1.4, "name": "Broadcom"}, {"symbol": "JPM", "weight": 1.2, "name": "JPMorgan Chase"},
            {"symbol": "TSLA", "weight": 1.1, "name": "Tesla"}, {"symbol": "UNH", "weight": 1.1, "name": "UnitedHealth"},
            {"symbol": "XOM", "weight": 1.0, "name": "Exxon Mobil"}, {"symbol": "V", "weight": 0.9, "name": "Visa"},
            {"symbol": "MA", "weight": 0.8, "name": "Mastercard"}, {"symbol": "PG", "weight": 0.8, "name": "Procter & Gamble"},
            {"symbol": "COST", "weight": 0.8, "name": "Costco"}, {"symbol": "JNJ", "weight": 0.7, "name": "Johnson & Johnson"},
            {"symbol": "HD", "weight": 0.7, "name": "Home Depot"}, {"symbol": "ABBV", "weight": 0.7, "name": "AbbVie"},
            {"symbol": "WMT", "weight": 0.7, "name": "Walmart"}, {"symbol": "NFLX", "weight": 0.6, "name": "Netflix"},
            {"symbol": "BAC", "weight": 0.6, "name": "Bank of America"}, {"symbol": "CRM", "weight": 0.6, "name": "Salesforce"},
            {"symbol": "AMD", "weight": 0.6, "name": "AMD"},
        ],
    },
    "VOO": {
        "name": "Vanguard S&P 500 ETF",
        "total_holdings": 503,
        "holdings": [
            {"symbol": "AAPL", "weight": 7.1, "name": "Apple"}, {"symbol": "MSFT", "weight": 6.8, "name": "Microsoft"},
            {"symbol": "NVDA", "weight": 6.2, "name": "NVIDIA"}, {"symbol": "AMZN", "weight": 3.8, "name": "Amazon"},
            {"symbol": "META", "weight": 2.6, "name": "Meta Platforms"}, {"symbol": "GOOGL", "weight": 2.1, "name": "Alphabet A"},
            {"symbol": "GOOG", "weight": 1.8, "name": "Alphabet C"}, {"symbol": "BRK.B", "weight": 1.7, "name": "Berkshire Hathaway"},
            {"symbol": "LLY", "weight": 1.6, "name": "Eli Lilly"}, {"symbol": "AVGO", "weight": 1.5, "name": "Broadcom"},
            {"symbol": "JPM", "weight": 1.3, "name": "JPMorgan Chase"}, {"symbol": "TSLA", "weight": 1.2, "name": "Tesla"},
            {"symbol": "UNH", "weight": 1.2, "name": "UnitedHealth"}, {"symbol": "XOM", "weight": 1.1, "name": "Exxon Mobil"},
            {"symbol": "V", "weight": 1.0, "name": "Visa"}, {"symbol": "MA", "weight": 0.9, "name": "Mastercard"},
            {"symbol": "PG", "weight": 0.9, "name": "Procter & Gamble"}, {"symbol": "COST", "weight": 0.9, "name": "Costco"},
            {"symbol": "JNJ", "weight": 0.8, "name": "Johnson & Johnson"}, {"symbol": "HD", "weight": 0.8, "name": "Home Depot"},
            {"symbol": "ABBV", "weight": 0.8, "name": "AbbVie"}, {"symbol": "WMT", "weight": 0.7, "name": "Walmart"},
            {"symbol": "NFLX", "weight": 0.7, "name": "Netflix"}, {"symbol": "BAC", "weight": 0.7, "name": "Bank of America"},
            {"symbol": "CRM", "weight": 0.7, "name": "Salesforce"},
        ],
    },
    "VGT": {
        "name": "Vanguard Info Tech ETF",
        "total_holdings": 316,
        "holdings": [
            {"symbol": "AAPL", "weight": 16.2, "name": "Apple"}, {"symbol": "MSFT", "weight": 14.8, "name": "Microsoft"},
            {"symbol": "NVDA", "weight": 13.5, "name": "NVIDIA"}, {"symbol": "AVGO", "weight": 4.8, "name": "Broadcom"},
            {"symbol": "AMD", "weight": 2.0, "name": "AMD"}, {"symbol": "CRM", "weight": 1.8, "name": "Salesforce"},
            {"symbol": "ADBE", "weight": 1.6, "name": "Adobe"}, {"symbol": "QCOM", "weight": 1.5, "name": "Qualcomm"},
            {"symbol": "TXN", "weight": 1.4, "name": "Texas Instruments"}, {"symbol": "INTU", "weight": 1.3, "name": "Intuit"},
            {"symbol": "AMAT", "weight": 1.2, "name": "Applied Materials"}, {"symbol": "PANW", "weight": 1.1, "name": "Palo Alto Networks"},
            {"symbol": "ADP", "weight": 1.0, "name": "ADP"}, {"symbol": "KLAC", "weight": 0.9, "name": "KLA Corp"},
            {"symbol": "SNPS", "weight": 0.9, "name": "Synopsys"}, {"symbol": "CRWD", "weight": 0.8, "name": "CrowdStrike"},
            {"symbol": "CDNS", "weight": 0.8, "name": "Cadence Design"}, {"symbol": "MRVL", "weight": 0.7, "name": "Marvell Tech"},
            {"symbol": "FTNT", "weight": 0.7, "name": "Fortinet"}, {"symbol": "MU", "weight": 0.7, "name": "Micron"},
            {"symbol": "INTC", "weight": 0.5, "name": "Intel"}, {"symbol": "NOW", "weight": 0.9, "name": "ServiceNow"},
            {"symbol": "LRCX", "weight": 0.7, "name": "Lam Research"}, {"symbol": "MSCI", "weight": 0.5, "name": "MSCI"},
            {"symbol": "IT", "weight": 0.5, "name": "Gartner"},
        ],
    },
    "SCHD": {
        "name": "Schwab US Dividend Equity",
        "total_holdings": 103,
        "holdings": [
            {"symbol": "ABBV", "weight": 4.5, "name": "AbbVie"}, {"symbol": "HD", "weight": 4.2, "name": "Home Depot"},
            {"symbol": "AMGN", "weight": 4.1, "name": "Amgen"}, {"symbol": "CSCO", "weight": 4.0, "name": "Cisco"},
            {"symbol": "PEP", "weight": 3.8, "name": "PepsiCo"}, {"symbol": "MRK", "weight": 3.5, "name": "Merck"},
            {"symbol": "KO", "weight": 3.4, "name": "Coca-Cola"}, {"symbol": "AVGO", "weight": 3.3, "name": "Broadcom"},
            {"symbol": "PFE", "weight": 3.0, "name": "Pfizer"}, {"symbol": "TXN", "weight": 2.8, "name": "Texas Instruments"},
            {"symbol": "CVX", "weight": 2.7, "name": "Chevron"}, {"symbol": "VZ", "weight": 2.5, "name": "Verizon"},
            {"symbol": "BLK", "weight": 2.3, "name": "BlackRock"}, {"symbol": "UPS", "weight": 2.2, "name": "UPS"},
            {"symbol": "LMT", "weight": 2.0, "name": "Lockheed Martin"}, {"symbol": "USB", "weight": 1.8, "name": "US Bancorp"},
            {"symbol": "SCHW", "weight": 1.7, "name": "Schwab"}, {"symbol": "MMM", "weight": 1.5, "name": "3M"},
            {"symbol": "ITW", "weight": 1.4, "name": "Illinois Tool Works"}, {"symbol": "EOG", "weight": 1.3, "name": "EOG Resources"},
            {"symbol": "CMI", "weight": 1.2, "name": "Cummins"}, {"symbol": "FAST", "weight": 1.1, "name": "Fastenal"},
            {"symbol": "PAYX", "weight": 1.0, "name": "Paychex"}, {"symbol": "O", "weight": 0.9, "name": "Realty Income"},
            {"symbol": "KMB", "weight": 0.8, "name": "Kimberly-Clark"},
        ],
    },
    "XLK": {
        "name": "Technology Select Sector SPDR",
        "total_holdings": 68,
        "holdings": [
            {"symbol": "AAPL", "weight": 21.5, "name": "Apple"}, {"symbol": "MSFT", "weight": 20.8, "name": "Microsoft"},
            {"symbol": "NVDA", "weight": 18.2, "name": "NVIDIA"}, {"symbol": "AVGO", "weight": 5.1, "name": "Broadcom"},
            {"symbol": "CRM", "weight": 2.1, "name": "Salesforce"}, {"symbol": "AMD", "weight": 1.9, "name": "AMD"},
            {"symbol": "ADBE", "weight": 1.7, "name": "Adobe"}, {"symbol": "QCOM", "weight": 1.5, "name": "Qualcomm"},
            {"symbol": "TXN", "weight": 1.4, "name": "Texas Instruments"}, {"symbol": "INTU", "weight": 1.3, "name": "Intuit"},
            {"symbol": "AMAT", "weight": 1.2, "name": "Applied Materials"}, {"symbol": "PANW", "weight": 1.1, "name": "Palo Alto Networks"},
            {"symbol": "ADP", "weight": 1.0, "name": "ADP"}, {"symbol": "KLAC", "weight": 0.9, "name": "KLA"},
            {"symbol": "NOW", "weight": 0.9, "name": "ServiceNow"},
        ],
    },
    "XLF": {
        "name": "Financial Select Sector SPDR",
        "total_holdings": 72,
        "holdings": [
            {"symbol": "BRK.B", "weight": 13.2, "name": "Berkshire Hathaway"}, {"symbol": "JPM", "weight": 10.5, "name": "JPMorgan Chase"},
            {"symbol": "V", "weight": 7.8, "name": "Visa"}, {"symbol": "MA", "weight": 6.2, "name": "Mastercard"},
            {"symbol": "BAC", "weight": 4.1, "name": "Bank of America"}, {"symbol": "WFC", "weight": 3.2, "name": "Wells Fargo"},
            {"symbol": "GS", "weight": 2.8, "name": "Goldman Sachs"}, {"symbol": "SPGI", "weight": 2.5, "name": "S&P Global"},
            {"symbol": "AXP", "weight": 2.3, "name": "Amex"}, {"symbol": "MS", "weight": 2.2, "name": "Morgan Stanley"},
            {"symbol": "BLK", "weight": 2.0, "name": "BlackRock"}, {"symbol": "C", "weight": 1.9, "name": "Citigroup"},
            {"symbol": "SCHW", "weight": 1.8, "name": "Schwab"},
        ],
    },
    "XLV": {
        "name": "Health Care Select Sector SPDR",
        "total_holdings": 63,
        "holdings": [
            {"symbol": "LLY", "weight": 11.8, "name": "Eli Lilly"}, {"symbol": "UNH", "weight": 9.5, "name": "UnitedHealth"},
            {"symbol": "JNJ", "weight": 6.8, "name": "Johnson & Johnson"}, {"symbol": "ABBV", "weight": 6.2, "name": "AbbVie"},
            {"symbol": "MRK", "weight": 5.5, "name": "Merck"}, {"symbol": "TMO", "weight": 3.8, "name": "Thermo Fisher"},
            {"symbol": "ABT", "weight": 3.5, "name": "Abbott"}, {"symbol": "AMGN", "weight": 3.2, "name": "Amgen"},
            {"symbol": "DHR", "weight": 2.8, "name": "Danaher"}, {"symbol": "PFE", "weight": 2.5, "name": "Pfizer"},
            {"symbol": "ISRG", "weight": 2.3, "name": "Intuitive Surgical"}, {"symbol": "BMY", "weight": 2.0, "name": "Bristol-Myers"},
            {"symbol": "GILD", "weight": 1.8, "name": "Gilead"}, {"symbol": "VRTX", "weight": 1.7, "name": "Vertex"},
            {"symbol": "REGN", "weight": 1.6, "name": "Regeneron"},
        ],
    },
    "XLE": {
        "name": "Energy Select Sector SPDR",
        "total_holdings": 23,
        "holdings": [
            {"symbol": "XOM", "weight": 22.5, "name": "Exxon Mobil"}, {"symbol": "CVX", "weight": 15.8, "name": "Chevron"},
            {"symbol": "COP", "weight": 8.2, "name": "ConocoPhillips"}, {"symbol": "SLB", "weight": 5.1, "name": "Schlumberger"},
            {"symbol": "EOG", "weight": 4.8, "name": "EOG Resources"}, {"symbol": "MPC", "weight": 4.5, "name": "Marathon Petroleum"},
            {"symbol": "PSX", "weight": 3.2, "name": "Phillips 66"}, {"symbol": "VLO", "weight": 3.0, "name": "Valero"},
            {"symbol": "WMB", "weight": 2.8, "name": "Williams Cos"}, {"symbol": "OKE", "weight": 2.5, "name": "ONEOK"},
            {"symbol": "HES", "weight": 2.3, "name": "Hess"}, {"symbol": "OXY", "weight": 2.2, "name": "Occidental"},
            {"symbol": "HAL", "weight": 1.8, "name": "Halliburton"},
        ],
    },
    "XLI": {
        "name": "Industrial Select Sector SPDR",
        "total_holdings": 78,
        "holdings": [
            {"symbol": "GE", "weight": 5.2, "name": "GE Aerospace"}, {"symbol": "CAT", "weight": 4.8, "name": "Caterpillar"},
            {"symbol": "RTX", "weight": 4.5, "name": "RTX Corp"}, {"symbol": "HON", "weight": 3.8, "name": "Honeywell"},
            {"symbol": "UNP", "weight": 3.5, "name": "Union Pacific"}, {"symbol": "BA", "weight": 3.2, "name": "Boeing"},
            {"symbol": "DE", "weight": 3.0, "name": "Deere"}, {"symbol": "LMT", "weight": 2.8, "name": "Lockheed Martin"},
            {"symbol": "UPS", "weight": 2.5, "name": "UPS"}, {"symbol": "ETN", "weight": 2.3, "name": "Eaton"},
            {"symbol": "NOC", "weight": 2.0, "name": "Northrop Grumman"}, {"symbol": "GD", "weight": 1.7, "name": "General Dynamics"},
            {"symbol": "MMM", "weight": 1.5, "name": "3M"}, {"symbol": "ITW", "weight": 1.4, "name": "Illinois Tool Works"},
            {"symbol": "EMR", "weight": 1.2, "name": "Emerson Electric"},
        ],
    },
    "SOXX": {
        "name": "iShares Semiconductor ETF",
        "total_holdings": 30,
        "holdings": [
            {"symbol": "NVDA", "weight": 10.2, "name": "NVIDIA"}, {"symbol": "AVGO", "weight": 8.5, "name": "Broadcom"},
            {"symbol": "AMD", "weight": 7.8, "name": "AMD"}, {"symbol": "QCOM", "weight": 6.5, "name": "Qualcomm"},
            {"symbol": "TXN", "weight": 5.8, "name": "Texas Instruments"}, {"symbol": "AMAT", "weight": 5.2, "name": "Applied Materials"},
            {"symbol": "MU", "weight": 4.8, "name": "Micron"}, {"symbol": "LRCX", "weight": 4.5, "name": "Lam Research"},
            {"symbol": "KLAC", "weight": 4.2, "name": "KLA Corp"}, {"symbol": "INTC", "weight": 3.8, "name": "Intel"},
            {"symbol": "MRVL", "weight": 3.5, "name": "Marvell"}, {"symbol": "SNPS", "weight": 3.2, "name": "Synopsys"},
            {"symbol": "CDNS", "weight": 3.0, "name": "Cadence"}, {"symbol": "ADI", "weight": 2.8, "name": "Analog Devices"},
            {"symbol": "NXPI", "weight": 2.5, "name": "NXP Semi"},
        ],
    },
    "ARKK": {
        "name": "ARK Innovation ETF",
        "total_holdings": 35,
        "holdings": [
            {"symbol": "TSLA", "weight": 11.5, "name": "Tesla"}, {"symbol": "COIN", "weight": 8.2, "name": "Coinbase"},
            {"symbol": "ROKU", "weight": 7.5, "name": "Roku"}, {"symbol": "SQ", "weight": 6.8, "name": "Block"},
            {"symbol": "RKLB", "weight": 5.5, "name": "Rocket Lab"}, {"symbol": "PATH", "weight": 5.0, "name": "UiPath"},
            {"symbol": "PLTR", "weight": 4.8, "name": "Palantir"}, {"symbol": "SHOP", "weight": 4.2, "name": "Shopify"},
            {"symbol": "DKNG", "weight": 3.8, "name": "DraftKings"}, {"symbol": "HOOD", "weight": 3.5, "name": "Robinhood"},
            {"symbol": "U", "weight": 3.2, "name": "Unity"}, {"symbol": "CRSP", "weight": 2.8, "name": "CRISPR"},
            {"symbol": "BEAM", "weight": 2.5, "name": "Beam Therapeutics"}, {"symbol": "EXAS", "weight": 2.2, "name": "Exact Sciences"},
            {"symbol": "TWLO", "weight": 2.0, "name": "Twilio"},
        ],
    },
}


def get_etf_exposure(ticker: str) -> list[dict]:
    """Find which ETFs hold a given ticker and its weight in each."""
    exposures = []
    for etf_symbol, etf_data in ETF_HOLDINGS.items():
        for holding in etf_data["holdings"]:
            if holding["symbol"] == ticker:
                exposures.append({
                    "etf": etf_symbol,
                    "etf_name": etf_data["name"],
                    "weight": holding["weight"],
                })
                break
    return sorted(exposures, key=lambda x: x["weight"], reverse=True)
